#!/bin/sh

cd ..
cd Q1

rm 1-1 2>/dev/null
rm 1-2 2>/dev/null
rm 1-3 2>/dev/null
rm 1-4 2>/dev/null
rm 1-4-2 2>/dev/null
rm 1-5 2>/dev/null
rm 1-6 2>/dev/null

cd ..
cd Q2

rm 2-1 2>/dev/null
rm 2-2 2>/dev/null
rm 2-3 2>/dev/null
rm 2-4 2>/dev/null
rm 2-5 2>/dev/null
rm 2-6 2>/dev/null
rm 2-7 2>/dev/null
rm 2-8 2>/dev/null

cd ..
cd Q3

rm 3-1 2>/dev/null
rm 3-2 2>/dev/null
rm 3-3 2>/dev/null
rm 3-4 2>/dev/null
rm 3-5 2>/dev/null
rm 3-6 2>/dev/null
rm 3-7 2>/dev/null
rm 3-8 2>/dev/null
rm 3-9 2>/dev/null

cd ..
